VERSION 0.8

uv:
    FROM ghcr.io/astral-sh/uv:0.4.12

    SAVE ARTIFACT /uv uv

deps:
    FROM python:3.12-slim-bookworm

    ENV UV_COMPILE_BYTECODE=0

    WORKDIR /work

    COPY +uv/uv /usr/local/bin/uv
    COPY pyproject.toml uv.lock README.md .

    RUN uv sync --frozen --no-install-project

src:
    FROM +deps

    COPY --dir src README.md .

check:
    FROM +src

    RUN uv sync --frozen --no-install-project --extra dev

    RUN uv run black --check .
    RUN uv run ruff check .

build:
    FROM +src

    RUN uv build --wheel

    SAVE ARTIFACT dist dist

test:
    FROM +src

    COPY --dir tests .

    RUN uv sync --frozen --extra dev
    RUN uv run pytest .

docker:
    FROM python:3.12-slim

	ARG container=hello
	ARG tag=latest

    WORKDIR /app

    COPY +build/dist dist

    RUN pip install dist/*.whl

    ENTRYPOINT ["hello"]
	SAVE IMAGE ${container}:${tag}

github:
    FROM scratch

    COPY +build/dist dist

    SAVE ARTIFACT dist/* hello.whl