VERSION 0.8

deps:
    FROM golang:1.23.0

    WORKDIR /work

    RUN mkdir -p /go/cache && mkdir -p /go/modcache
    ENV GOCACHE=/go/cache
    ENV GOMODCACHE=/go/modcache
    CACHE --persist --sharing shared /go

    COPY go.mod go.sum .
    RUN go mod download

src:
    FROM +deps

    CACHE --persist --sharing shared /go

    COPY --dir cmd .

check:
    FROM +src

    RUN gofmt -l . | grep . && exit 1 || exit 0
    RUN go vet ./...

build:
    FROM +src

    ARG GOOS
    ARG GOARCH
    ARG version="v0.0.0"

    ENV CGO_ENABLED=0
    RUN go build -ldflags="-extldflags=-static -X main.version=$version" -o bin/hello cmd/main.go

    SAVE ARTIFACT bin/hello hello

test:
    FROM +build

    RUN go test ./...

github:
    FROM scratch

    ARG version="v0.0.0"

    ARG TARGETOS
    ARG TARGETARCH
    ARG USERPLATFORM

    COPY \
        --platform=$USERPLATFORM \
        (+build/hello \
        --GOOS=$TARGETOS \
        --GOARCH=$TARGETARCH \
        --version=$version) bin/hello

    SAVE ARTIFACT bin/hello hello

docker:
    FROM debian:bookworm-slim
    WORKDIR /workspace

    ARG container="hello"
    ARG tag="latest"
    ARG version="v0.0.0"

    ARG TARGETOS
    ARG TARGETARCH
    ARG USERPLATFORM

    COPY \
        --platform=$USERPLATFORM \
        (+build/hello \
        --GOOS=$TARGETOS \
        --GOARCH=$TARGETARCH \
        --version=$version) /usr/local/bin/hello

    ENTRYPOINT ["/usr/local/bin/hello"]
    SAVE IMAGE ${container}:${tag}