name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  id-token: write
  contents: write
  packages: write
jobs:
  ci:
    uses: input-output-hk/catalyst-forge/.github/workflows/ci.yml@ci/v1.1.0
    with:
      forge_version: 0.2.0